src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $carrierName = null;

    #[ORM\Column]
    private ?float $carrierPrice = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $delivery = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'myOrder', cascade: ['persist'])] //ajouter la cascade pour sauvegarder les détails de commande
    private Collection $orderDetails;

    /*
    * 1 : En attente de payment
    * 2 : Payement validé
    * 3 : Expédié 
    */
    #[ORM\Column]
    private ?int $state = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $stripe_session_id = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    // calcul du total HT de tous les produits de la commande
    public function getTotalWt()
    {
        $totalTtc = 0;
        $products = $this->getOrderDetails();
        foreach ($products as $product) {
            $coef = 1 + ($product->getProductTva()/100);
            $totalTtc += $product->getProductPrice() * $coef * $product->getProductQuantity(); // calcul du total TTC sur le prix HT de chaque produit
        }
        return $totalTtc + $this->getCarrierPrice(); // ajout le prix de transport
    }

    // calcul du total TVA sur le prix HT de tous les produits de la commande
    public function getTotalTva()
    {
        $totalTva = 0;
        $products = $this->getOrderDetails();
        foreach ($products as $product) {
            $coef = $product->getProductTva()/100; // calcul du coefficient de TVA
            $totalTva += $coef * $product->getProductPrice(); // calcul du total TVA sur le prix HT de chaque produit
            return $totalTva;
        }

        return 300;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): static
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(float $carrierPrice): static
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): static
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripe_session_id;
    }

    public function setStripeSessionId(?string $stripe_session_id): static
    {
        $this->stripe_session_id = $stripe_session_id;

        return $this;
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use Dompdf\Dompdf;
use App\Repository\OrderRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class InvoiceController extends AbstractController
{
    /*
    * Impression facture PDF pour un utilisateur connecté
    * Vérication de la commande pour un utilisateur donné
    */
    #[Route('/compte/facture/impression/{id_order}', name: 'app_invoice_customer')]
    public function printForCustomer(OrderRepository $orderRepository, $id_order): Response
    {
        // Vérification de l'objer commande -Existe ?
        $order = $orderRepository->findOneById($id_order);

        if (!$order) {
            return $this->redirectToRoute('app_account');
        }

        // Vérification de l'objer commande -OK- pour l'utilisateur ?
        if ($order->getUser() != $this->getUser()) {
            return $this->redirectToRoute('app_account');
        }

        $dompdf = new Dompdf();

        $html = $this->renderView('invoice/index.html.twig', [
            'order' => $order,
        ]);

        $dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();

        $dompdf->stream('facture.pdf',[
            'Attachment' => false,
        ]);
        exit();
    }


    /*
    * Impression facture PDF pour un administrateur connecté
    * Vérication de la commande pour un utilisateur donné
    */
    #[Route('/admin/facture/impression/{id_order}', name: 'app_invoice_admin')]
    public function printForAdmin(OrderRepository $orderRepository, $id_order): Response
    {
        // Vérification de l'objer commande -Existe ?
        $order = $orderRepository->findOneById($id_order);

        if (!$order) {
            return $this->redirectToRoute('admin');
        }

        $dompdf = new Dompdf();

        $html = $this->renderView('invoice/index.html.twig', [
            'order' => $order,
        ]);

        $dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();

        $dompdf->stream('facture.pdf',[
            'Attachment' => false,
        ]);
        exit();
    }
}

templates/invoice/index.html.twig
<!doctype html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Facture</title>
        <style>
            .text-center {
                text-align: center;
            }

            .text-right {
                text-align: right;
            }

            .text-left {
                text-align: left;
            }

            body {
                font-family: Roboto, sans-serif;
            }

            h1 {
                color: #333;
                text-align: center;
            }

            table {
                border-collapse: collapse;
            }

            table td, table th {
                border-top: 1px solid #ccc;
                padding: 10px;
            }
        </style>    
    </head>
    <body>
        <div class="text-center">
            <h3>Facture commande N° {{ order.id }}</h3>
            <table style="width: 100%; border-bottom: 1px solid gray;">
                <tr>
                    <td style="width: 49%">
                        <strong>SecuProShop</strong></br>
                        Nom adresse <br>
                        code postal, ville, France</br>
                        Email :  contact@secuproshop.com</br>
                        Tel : 01 23 45 67 89 <br>        
                    </td>
                    <td class="text-right">
                        {{ order.delivery|raw }}
                    </td>
                </tr>
            </table> 
        </div>   
        <h5>Votre commande</h5>     
        
            <table style="width: 100%;">
            <thead>
                <tr>
                    <th scope="col" class="text-left">Produit</th>
                    <th scope="col" class="text-left">Quantité</th>
                    <th scope="col" class="text-left">Prix unitaire</th>
                    <th scope="col" class="text-left">Total TVA</th>
                    <th scope="col" class="text-right">Total TTC</th>
                </tr>
            </thead>
            <tbody>
                {% for product in order.orderDetails %}
                    <tr>
                        <td>{{ product.productName }}</td>
                        <td>{{ product.productQuantity }}</td>
                        <td>{{ product.productPrice|price }}</td>
                        <td>{{ product.productTva }} %</td>
                        {% set coef = 1 + (product.productTva / 100) %}    
                        <td class="text-right">{{ ((product.productPrice * coef) * product.productQuantity)|price }}</td>
                    </tr>    
                {% endfor %}
                <tr>
                    <td>{{ order.carrierName }}</td>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td class="text-right">{{ order.carrierPrice|price }}</td>
                </tr>
            </tbody>
        </table>
            
        <div class="text-right" style="margin-top: 20px">
        <strong>Total HT : </strong> {{ (order.totalWt - order.totalTva)|price }}</br>
        <strong>Total TVA : </strong> {{ order.totalTva|price }} </br>
        <strong>Total TTC : </strong> {{ order.totalWt|price }}
    </div>
    </body>
</html>